### ISSUE TITLE
PDF: table balancing algorithm not working well

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#845] opened 2022-11-08 02:11 UTC
From ISO 10303-15 (https://github.com/metanorma/iso-10303-detached-docs):
<img width="613" alt="Screen Shot 2022-11-08 at 10 10 35 AM" src="https://user-images.githubusercontent.com/11865/200457792-1249afde-6b6f-4c81-9f71-ddc915affd90.png">
<img width="560" alt="Screen Shot 2022-11-08 at 10 11 01 AM" src="https://user-images.githubusercontent.com/11865/200457868-a1fd64ba-49b6-41e2-9aa2-5522d5510bfc.png">

**Comment by Intelligent2013** [comment] 2022-11-08 09:42
There are a few issues:
- standards's number without break (https://github.com/metanorma/mn-native-pdf/issues/353#issuecomment-1236111289)
  ![image](https://user-images.githubusercontent.com/5559926/200530304-86c9b2a4-aa96-4d7b-b568-ebb0bfe23e3c.png)

  ![image](https://user-images.githubusercontent.com/5559926/200530229-41e012d3-089b-4e5d-acda-b81bb0632893.png)
- long text without spaces in 3rd column:
   ![image](https://user-images.githubusercontent.com/5559926/200528336-7d281a79-bcd4-464f-aca6-208fc3d9edca.png)

Will fix.

**Comment by Intelligent2013** [comment] 2022-11-08 18:47
Wrong auto-layout algorithm for source code markup:
![image](https://user-images.githubusercontent.com/5559926/200649291-8d24a529-078c-45fb-a7d8-0ef5bd7af68f.png)

The reason: only first part of source code text renders in the monospace font on the algorithm preliminary step:
![image](https://user-images.githubusercontent.com/5559926/200649490-32c5d1e8-de50-4347-afdd-2708840eaf36.png)

**Comment by Intelligent2013** [comment] 2022-11-08 20:15
Fixed:
![image](https://user-images.githubusercontent.com/5559926/200665272-3f216f8c-3bf5-4e18-8820-318fff951571.png)

But no effect in the resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/200665382-cd946f2e-af51-414f-a49e-4174612650fe.png)

The preliminary reason: in Apache IF there are two `<font ` elements `<font family="Noto Sans Mono"/>` and `<font family="Courier New"/>` and IF parser doesn't process correctly such case:
```xml
<font family="Courier New"/>
<id name="table_if_tab_C.1_4_4_p_1_1"/>
<text x="0" y="11192" next-is-space="true" foi:struct-ref="81b">&lt;ownedComment … xmi:</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="120000" y="11192" next-is-space="true" foi:struct-ref="81b">type=</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="150000" y="11192" next-is-space="true" foi:struct-ref="81b">"uml:</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="180000" y="11192" next-is-space="true" foi:struct-ref="81b">Comment"&gt;…&lt;/</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="252000" y="11192" foi:struct-ref="81b">ownedComment&gt;</text>
<font family="Cambria"/>
<text x="330000" y="11192" foi:struct-ref="81c"> </text>
<id name="table_if_tab_C.1_4_4_p_1_1_end"/>
<text x="332200" y="11192" foi:struct-ref="81d">end</text>
```

**Comment by Intelligent2013** [comment] 2022-11-08 20:34
The table `C.1` marked as `landscape` in the source STS XML:
```xml
<table-wrap id="tab_C.1" orientation="landscape" position="float"><?Table Table_MMinus?>
<label>Table C.1</label><caption><title>EXPRESS/Information modelling constructs and the equivalent SysML modelling constructs with CXMI constructs</title>
</caption>
```

But PDF renders wrong: https://github.com/metanorma/mn-native-pdf/issues/448.

**Comment by Intelligent2013** [comment] 2022-11-11 11:05
Wrong `sourcecode` width determination in auto-layout algorithm:
![image](https://user-images.githubusercontent.com/5559926/201327400-1dba02a3-0ec4-4846-9f86-2415190cfbd9.png)

Issues:
- the internal mark `end` placed on the next line
- `sourcecode` text should be split by newline char, and each chunk should be rendered separaterely, for correct end position determination.

**Comment by Intelligent2013** [comment] 2022-11-11 18:38
Fixed:
![image](https://user-images.githubusercontent.com/5559926/201408729-494d28d1-60d3-4b0b-a140-df7e3489479d.png)


![image](https://user-images.githubusercontent.com/5559926/201408602-e58a3a3e-f168-4a02-aeb6-80b82fed3894.png)

**Comment by Intelligent2013** [comment] 2022-11-30 19:23
Regression after latest updates for non-breaking standard's numbers:
![image](https://user-images.githubusercontent.com/5559926/204889541-11924d5c-50fd-4d4b-80db-c8db8641844d.png)

**Comment by Intelligent2013** [comment] 2022-11-30 20:39
Fixed:
![image](https://user-images.githubusercontent.com/5559926/204903266-b7c01866-a20b-4f91-8bbd-12f8386ae99c.png)

**Closed by Intelligent2013** 2022-11-30 20:39 UTC
Labels: bug
