### ISSUE TITLE
(URGENT) Word: French title displayed in broken box

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#792] opened 2022-09-11 12:04 UTC
<img width="804" alt="Screen Shot 2022-09-11 at 8 03 45 PM" src="https://user-images.githubusercontent.com/11865/189526545-c260696f-8405-4e8c-b903-47e4ef4b45f8.png">

Seems like something wrong with the HTML/CSS there. This is the Word Edited DIS template.

**Comment by opoudjis** [comment] 2022-09-15 00:49
Duplicate of https://github.com/metanorma/metanorma-iso/issues/783 . Does not impact rendering.

**Closed by opoudjis** 2022-09-15 00:49 UTC
Labels: bug
