### ISSUE TITLE
Missing translations to French

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#418] opened 2020-09-03 19:46 UTC
Translation to French is needed for:

- "Reference number" in the front page footer

Original:
![image](https://user-images.githubusercontent.com/55683568/92159064-1a46ad80-ee2d-11ea-96dd-9b51d907dc44.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/92158818-c4720580-ee2c-11ea-8d22-4a3e2429971f.png)

- "All rights reserved" in the footer of other pages

Original:
![image](https://user-images.githubusercontent.com/55683568/92158945-eb303c00-ee2c-11ea-8499-dfd20bf1ee35.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/92159108-2af72380-ee2d-11ea-83a2-0570f8e16037.png)

- whole Copyright

Original:
![image](https://user-images.githubusercontent.com/55683568/92159224-5a0d9500-ee2d-11ea-8c24-b913920b8e73.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/92159251-6396fd00-ee2d-11ea-89e2-f05bca25d41e.png)

- Keywords: DEPRECATED, CAUTION, WARNING. Probably there are more keywords to be translated, but I found these in ISO Rice IS. Keywords such as NOTE and SOURCE are spelled the same in English and French, but I'm noting these in case some document attribute or other solution of this issue will be applied to Chinese (and/or some other languages) as well. 

Original (example):
![image](https://user-images.githubusercontent.com/55683568/92159704-1a937880-ee2e-11ea-962e-e7c01804d0b1.png)

Generated (example):
![image](https://user-images.githubusercontent.com/55683568/92159620-ff286d80-ee2d-11ea-90d4-22db0371f57d.png)

- "Price based on #x# pages" at the end of the last page

Original:
![image](https://user-images.githubusercontent.com/55683568/92158896-d94e9900-ee2c-11ea-9d26-64dff0de15f7.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/92159139-377b7c00-ee2d-11ea-9c11-fe45a3a45fd5.png)

- References should probably be autofetched in native language, but I opened a separate ticket (https://github.com/metanorma/metanorma-iso/issues/417) for this, because I believe solution is more complex and different from the issues above.

**Comment by opoudjis** [comment] 2020-09-04 12:24
Thank you; but I am putting this in medium rather than high priority, because of the large backlog

**Comment by opoudjis** [comment] 2020-10-08 01:36
In order to address this issue globally, I am creating a lexicon to be added to the Presentation XML, which PDF generation can draw on—since this is not text that will be supplied from the Presentation XML itself, it will be used to recreate the cover page independently.

**Comment by ronaldtse** [comment] 2020-10-08 02:33
Thanks @opoudjis for updating this. https://github.com/metanorma/bipm-si-brochure/pull/23 is also dependent on this issue, for "see" vs "voir", where I believe a template is most suitable:

Just for example:
```xml
<internationalization_template id="cross_reference_page">
<template lang="en">{{ reference_title }}, _see_ p. {{ page_number  }}</template>
<template lang="fr">{{ reference_title }}, _voir_ p. {{ page_number  }}</template>
</internationalization_template>
```

**Comment by opoudjis** [comment] 2020-10-14 10:06
This will be addressed by shoving the entire contents of the current YAML internationalisation mapping into `local-bibdata`, under `i18nyaml`. That way, all internationalisation mappings can be looked up.

**Comment by opoudjis** [comment] 2020-10-14 11:45
The proposed template is a possible approach, but I'm not adopting it, because it is utterly useless for XSLT. (This whole exercise is to make life easy for Alex D in XSLT; how does Liquid, of all things, do that?!)

**Comment by opoudjis** [comment] 2020-10-14 12:20
Translating boilerplate document for ISO

**Comment by opoudjis** [comment] 2020-10-14 13:03
@anermina Have addressed DOC/HTML, #428 is for PDF; request you check both as they become available. Reopen this ticket only if there is a problem in DOC/HTML.

@Intelligent2013, @anermina: this is the French Rice document (no PDF).

[rice-fr.zip](https://github.com/metanorma/metanorma-iso/files/5378313/rice-fr.zip)

**Comment by opoudjis** [comment] 2020-10-14 13:22
And for BIPM: "see" is translated into "voir" in /local_bibdata/i18nyaml/ii18n_see

**Comment by anermina** [comment] 2020-10-14 13:55
Ok, thanks @opoudjis .

**Comment by anermina** [comment] 2020-11-08 21:22
PDF:

**Comment by anermina** [comment] 2020-11-08 21:29
Sorry for the delay with re-checking this document.

I'm reopening this issue due to the following notes:

1. Title is generated in English in DOC, while in French in PDF.

DOC:
![image](https://user-images.githubusercontent.com/55683568/98484553-a354d900-2210-11eb-870e-c75edbe28cd1.png)

PDF:
![image](https://user-images.githubusercontent.com/55683568/98484563-c4b5c500-2210-11eb-8d21-c9480013d6d1.png)

2. Different keywords were used in translation of the word "part" in DOC and PDF. According to Google Translate, both translations are correct, but we need to match the translations.

DOC:
![image](https://user-images.githubusercontent.com/55683568/98484583-eadb6500-2210-11eb-9fd6-c1fb276d6a24.png)

PDF:
![image](https://user-images.githubusercontent.com/55683568/98484576-deefa300-2210-11eb-992a-52f47b63e3eb.png)

**Comment by opoudjis** [comment] 2020-11-23 11:03
I cannot reproduce this: can you try again? I'm getting the attached, compiling mn-samples-iso/sources/international-standard/rice-fr.adoc .

[Αρχειοθήκη.zip](https://github.com/metanorma/metanorma-iso/files/5582421/default.zip)

**Comment by opoudjis** [comment] 2020-12-07 11:39
Confirmed it's working on https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/international-standard/rice-fr.doc

[rice-fr.doc.zip](https://github.com/metanorma/metanorma-iso/files/5652377/rice-fr.doc.zip)

**Closed by opoudjis** 2020-12-07 11:39 UTC
Labels: enhancement
