### ISSUE TITLE
(URGENT) PDF: SVG rendering broken for some images

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#878] opened 2022-12-05 10:30 UTC
Ribose Metanorma mn2pdf version 1.52:
<img width="615" alt="Screen Shot 2022-12-05 at 6 28 47 PM" src="https://user-images.githubusercontent.com/11865/205614944-07e12da8-53f6-4c15-8a03-1faa48fd7842.png">

Ribose Metanorma mn2pdf version 1.50:
<img width="623" alt="Screen Shot 2022-12-05 at 6 29 08 PM" src="https://user-images.githubusercontent.com/11865/205615032-9d274859-effb-4907-82d1-cf5f79155fc3.png">

Document: https://github.com/metanorma/iso-19115-3/

This only happens in PDF, not Word or HTML.

@Intelligent2013 can you add some tests for this? Thanks.

**Comment by Intelligent2013** [comment] 2022-12-05 11:27
Confirmed. In mn2pdf v1.51 SVG renders ok also.
Issue occurs due the latest changes in https://github.com/metanorma/mn2pdf/commit/8450ea8ba38183d1b3a84e72aceb5552bd80b6df.

**Comment by Intelligent2013** [comment] 2022-12-05 13:48
Very strange, the issue occurs on Windows only (https://github.com/metanorma/mn2pdf/pull/161):
![image](https://user-images.githubusercontent.com/5559926/205652653-3a83d51e-f9c4-420d-bca3-77de3cc57390.png)

Will try to test locally on Ubuntu.

**Comment by ronaldtse** [comment] 2022-12-05 13:49
Interesting, but I'm on macOS and this PDF issue happens to me.

**Comment by Intelligent2013** [comment] 2022-12-05 14:31
On Ubuntu PDF renders ok:
![image](https://user-images.githubusercontent.com/5559926/205661469-5ab94296-7bc6-4c22-a02a-2ce5aa2a31bd.png)

**Comment by Intelligent2013** [comment] 2022-12-05 15:06
I hope issue fixed in mn2pdf v1.53.
But don't not close this issue, I will investigate why GH test ended successfully without patch on Ubuntu and Mac.

**Comment by Intelligent2013** [comment] 2022-12-20 11:19
The issue occurs on the Calibri font glyph processing. Previously, the issue have been occurred in Win only, because Calibri pre-installed yet. After manifest update, it occurs on all platforms (Win, Mac, Ubuntu) - https://github.com/metanorma/mn2pdf/actions/runs/3739747127.
Fix https://github.com/metanorma/mn2pdf/commit/8d6e4030721fdd3de97247e8df0604e03f4f30dd should solve the issue.

**Comment by Intelligent2013** [comment] 2022-12-20 11:36
Confirmed, the patch applied in mn2pdf 1.53 solved this issue (https://github.com/metanorma/mn2pdf/actions/runs/3740010156)

**Closed by Intelligent2013** 2022-12-20 11:36 UTC
Labels: bug
