### ISSUE TITLE
List: `[start=X]` list attribute doesn't seem to work

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#652] opened 2022-05-04 09:30 UTC
Encoding
```adoc
. [[item_7-2-a]]when multiple coordinates are present, each coordinate
shall be separated by a space;
. the order of the coordinates within the components shall be defined
in the specific CRS;
. CRS identifiers shall be listed at the end of the string, beginning
after the last coordinate and separated by a space. Formatting of
CRS identifiers shall follow rules <<item_7-2-c-1;to!item_7-2-c-4>>:
.. [[item_7-2-c-1]]all CRS identifiers shall be placed within a pair
of angle brackets [ < > ];
.. each CRS identifier shall be formatted as a free-form string with
no leading or trailing spaces;
.. the sequence order of the CRS identifiers shall be identical to
the sequence order of the associated coordinates in the human-readable
text string;
.. [[item_7-2-c-4]]when multiple CRS identifiers are present, each
shall be separated by a space.
. [[item_7-2-d]]the separator between the integer and fractional parts
of a coordinate shall be a full stop (point) on the line ( . );

Elements for axis abbreviation, axis direction and units of measure
are defined in CoordinateSystemAxis class (<<iso_19111_2019,table=47>>)
and used in the following rules.

For latitude and longitude coordinates the following rules
<<item_7-2-e;to!item_7-2-i>> shall apply:

[start=5]
. [[item_7-2-e]]the units of measure for latitude and longitude coordinates
shall follow the definition of the specific CRS;

. when sexagesimal degree representation is specified the following
rules <<item_7-2-f-1;to!item_7-2-f-2>> shall apply:
```

PDF:
<img width="506" alt="Screenshot 2022-05-04 at 5 29 01 PM" src="https://user-images.githubusercontent.com/11865/166655860-4a2f243b-484e-49e3-b760-bafd7c81a628.png">

Word:
<img width="730" alt="Screenshot 2022-05-04 at 5 29 39 PM" src="https://user-images.githubusercontent.com/11865/166655966-c0485e4b-0e3b-4ff0-8e45-ac584e847185.png">

From: https://github.com/metanorma/iso-6709/issues/12

**Comment by opoudjis** [comment] 2022-05-04 12:59
Duplicate of https://github.com/metanorma/isodoc/issues/247

**Closed by opoudjis** 2022-05-04 12:59 UTC
Labels: bug
