### ISSUE TITLE
Terms specified in the "ISO 10241-1 systematic order" results can no longer be referenced by concept mentions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#762] opened 2022-08-23 06:29 UTC
Here, "time of day" is defined as a concept. "basic time of day" (etc.) are defined as narrower concepts.

However, the "time of day" can no longer be used for concept mentions:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/11865/186086098-df8788d0-8ff8-4bf0-9162-9860aa48087f.png">

<img width="1111" alt="Screen Shot 2022-08-23 at 2 28 06 PM" src="https://user-images.githubusercontent.com/11865/186086317-784906d7-01f2-4e5e-9c7f-131fabf69ff3.png">

The source:

```adoc
=== time of day

{{time}} occurring within a {{calendar day}}
...

==== basis time of day

{{time of day}} in a {{basis time scale}}


==== UTC of day

{{time of day}} in {{UTC}}


==== local time of day

{{time of day}} in a {{local time}}
```

**Comment by Intelligent2013** [comment] 2022-08-23 08:53
@opoudjis FYI https://github.com/metanorma/metanorma-iso/issues/763#issuecomment-1223762767

**Comment by opoudjis** [comment] 2022-08-30 11:49
That snippet on its own processes fine, so that is not the issue. Turning to source document.

**Comment by ronaldtse** [comment] 2022-08-31 01:07
@opoudjis see this branch. This problem is real: https://github.com/CalConnect/iso-34000/pull/44

**Comment by opoudjis** [comment] 2022-08-31 09:52
You misdiagnosed the issue. The issue is that the hierarchy is not being recognised as a collection of terms, because some terms have subterms: the root is `clause`, not `terms`.

This is an assumption in standoc, that terms can't have subterms, which I did not override when I implemented subterms. Fixed.

**Comment by opoudjis** [comment] 2022-08-31 12:25
"only terms clauses can cross-reference terms clause" alert is being spuriously generated for xrefs between term chapters.

**Comment by ronaldtse** [comment] 2022-08-31 16:19
I'm on the Git gems and surely I'm not seeing the fix? The problem here is that the higher-level term is recognized as a clause, not a term.

<img width="715" alt="Screen Shot 2022-09-01 at 12 18 08 AM" src="https://user-images.githubusercontent.com/11865/187728509-4ae0a512-21c5-43c8-9b6b-5bf9f030671c.png">

**Comment by opoudjis** [comment] 2022-09-01 13:17
yes, the fix is in PR, and it depends on a breaking update to standoc, to address that issue.

https://github.com/metanorma/metanorma-iso/pull/780

**Comment by ronaldtse** [comment] 2022-09-02 17:59
Confirm working with https://github.com/metanorma/metanorma-iso/pull/780. Thanks!

**Closed** 2022-09-02 17:59 UTC
Labels: bug
