### ISSUE TITLE
User report: term source references broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#356] opened 2020-04-28 03:33 UTC
Previously term source was compiled to:
   [SOURCE: ISO 19107:2019, 4.6]

Now it generates:
  [SOURCE: 4.6 ]
 
(This also applies to metanorma-ogc)

```
== Normative references

* [[[ISO19107,ISO 19107:2019]]]
 
== Terms and definitions

=== boundary
 
set that represents the limit of an entity
  
[.source]
<<ISO19107,clause 4.6>>
```

Is compiling to:

```
ISO 19107:2019, Geographic information – Spatial schema
```

and

``` 
3.1
boundary
set that represents the limit of an entity

[SOURCE: 4.6 ]
```

Notice that the SOURCE is broken.

Gem versions:
```
> metanorma version
Metanorma 1.0.1
Metanorma::Cli 1.2.11
Metanorma::Standoc 1.3.24/IsoDoc 1.0.23
Metanorma::ISO 1.3.22
Metanorma::Iec 1.0.3
Metanorma::Ietf 2.0.3
Metanorma::Gb 1.3.4
Metanorma::Csd 1.3.3
Metanorma::Csa 1.4.3
Metanorma::M3d 1.3.12
Metanorma::Generic 1.4.6
Metanorma::UN 0.3.5
Metanorma::NIST 1.0.4
Metanorma::Ogc 1.0.4
Metanorma::ITU 1.0.7
 
And relaton versions from gem install relaton
Successfully installed relaton-calconnect-1.0.0
Successfully installed relaton-gb-1.0.0
Successfully installed relaton-ietf-1.0.0
Successfully installed relaton-itu-1.0.0
Successfully installed relaton-nist-1.0.0
Successfully installed relaton-omg-1.0.0
Successfully installed relaton-un-1.0.0
Successfully installed relaton-w3c-1.0.0
Successfully installed relaton-1.0.0
```

From @rggibb

**Comment by andrew2net** [comment] 2020-04-28 20:47
Please try relaton-iso v 1.0.1. Data structure changed search results. It's fixed in https://github.com/relaton/relaton-iso/issues/86#issuecomment-620708891

**Comment by rggibb** [comment] 2020-04-29 00:07
I'm using metanorma version:
Metanorma 1.0.3
Metanorma::Cli 1.2.11.1
Metanorma::Standoc 1.3.24/IsoDoc 1.0.23
Metanorma::ISO 1.3.22
Metanorma::Iec 1.0.4
Metanorma::Ietf 2.0.8
Metanorma::Gb 1.3.21
Metanorma::Csd 1.3.18
Metanorma::Csa 1.4.8
Metanorma::M3d 1.3.17
Metanorma::Generic 1.4.6
Metanorma::UN 0.3.6
Metanorma::NIST 1.0.5
Metanorma::Ogc 1.0.4
Metanorma::ITU 1.0.13

I installed:
gem install relaton-iso --version 1.0.1
Fetching: relaton-bib-1.0.0.gem (100%)
Successfully installed relaton-bib-1.0.0
Fetching: relaton-iso-bib-1.0.0.gem (100%)
Successfully installed relaton-iso-bib-1.0.0
Fetching: relaton-iec-1.0.0.gem (100%)
Successfully installed relaton-iec-1.0.0
Fetching: relaton-iso-1.0.1.gem (100%)
Successfully installed relaton-iso-1.0.1
Parsing documentation for relaton-bib-1.0.0
Installing ri documentation for relaton-bib-1.0.0
Parsing documentation for relaton-iso-bib-1.0.0
Installing ri documentation for relaton-iso-bib-1.0.0
Parsing documentation for relaton-iec-1.0.0
Installing ri documentation for relaton-iec-1.0.0
Parsing documentation for relaton-iso-1.0.1
Installing ri documentation for relaton-iso-1.0.1
Done installing documentation for relaton-bib, relaton-iso-bib, relaton-iec, relaton-iso after 3 seconds
4 gems installed

But this hasnt changed the behaviour .. Ron's initial thought was that metanorma wasnt using relaton 1.0.0 .. I'm not sure how the dependancies function, so not sure how to trace which version of relaton metanorma is actually using. Since the upgrade
gem list --local reports:
relaton (0.11.1)
relaton-bib (1.0.0, 0.9.2)
relaton-calconnect (0.7.0)
relaton-cli (0.9.0)
relaton-gb (0.12.0)
relaton-iec (1.0.0, 0.10.0)
relaton-ietf (0.12.1)
relaton-iev (0.1.5)
relaton-iso (1.0.1, 0.12.1)
relaton-iso-bib (1.0.0, 0.9.2)
relaton-itu (0.9.0)
relaton-nist (0.9.1)
relaton-ogc (0.7.3)
relaton-omg (0.3.0)
relaton-un (0.2.1)
relaton-w3c (0.1.0)

**Comment by opoudjis** [comment] 2020-04-29 10:06
Error in the source:

````
[bibliography]
== Normative references

* [[[ISO19107,ISO 19107:2019]]]
````

The `[bibliography]` is required by Asciidoctor, and no references will be processed without it. Without the tag, you get the behaviour reported; with it, you do not.

**Comment by rggibb** [comment] 2020-04-29 10:34
Except that in the actual source there is a [bibliography] statement, the construct is 

The parent file is:

[bibliography]
== Normative references

include::../sections-en/normref_core.adoc[]

and the include file has all the normative references in it.
 eg

* [[[ISO19107,ISO 19107:2019]]]

The quote from Ron was an incomplete summary, of a structure that has been working perfectly for over  a years and then failed last weekend after an upgrade of relaton

> Error in the source:
> 
> ```
> [bibliography]
> == Normative references
> 
> * [[[ISO19107,ISO 19107:2019]]]
> ```
> 
> The `[bibliography]` is required by Asciidoctor, and no references will be processed without it. Without the tag, you get the behaviour reported; with it, you do not.

**Comment by opoudjis** [comment] 2020-04-29 11:27
Since I can't replicate this, I'm at loss as to how to proceed, since we both are using relaton-iso 1.0.1.

Instead of installing gems locally, do "bundle update" in the directory where your document is, and report what happens.

**Comment by rggibb** [comment] 2020-04-29 11:37
Ron has let me know that he has managed to duplicate the error :
Hi Robert,

I actually just ran into this myself yesterday, so the good thing at least is I can reproduce it. Let me follow up and will let you know once it’s fixed… Thanks!

Ron

_____________________________________

Ronald Tse
Ribose Inc.

**Comment by rggibb** [comment] 2020-04-29 11:59
@ronaldtse @opoudjis .. but I've done a bundle update and a compile, and YES it is fixed, I'll paste the report in from bundle update. Because I had done a complete removal of metanorma and relaton, and reinstalled metanorma, in an attempt to get it working again, so there may still be an issue with dependencies.
 cheers Robert
bundle update
Fetching gem metadata from https://rubygems.org/...............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Fetching rake 12.3.3
Installing rake 12.3.3
Fetching public_suffix 4.0.4
Installing public_suffix 4.0.4
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using asciidoctor 2.0.10
Using asciimath 1.0.9
Using latex-decode 0.3.1
Fetching bibtex-ruby 5.1.4 (was 5.1.3)
Installing bibtex-ruby 5.1.4 (was 5.1.3)
Using bundler 2.1.4
Using camertron-eprun 1.1.1
Using cldr-plurals-runtime-rb 1.0.1
Fetching cnccs 0.1.5
Installing cnccs 0.1.5
Fetching concurrent-ruby 1.1.6
Installing concurrent-ruby 1.1.6
Using unf_ext 0.0.7.7 (x64-mingw32)
Using unf 0.1.4
Using domain_name 0.5.20190701
Using multipart-post 2.1.1
Fetching faraday 1.0.1
Installing faraday 1.0.1
Fetching ffi 1.12.2 (x64-mingw32)
Installing ffi 1.12.2 (x64-mingw32)
Fetching gb-agencies 0.0.6
Installing gb-agencies 0.0.6
Fetching rchardet 1.8.0
Installing rchardet 1.8.0
Fetching git 1.7.0 (was 1.6.0)
Installing git 1.7.0 (was 1.6.0)
Using htmlentities 4.3.4
Fetching image_size 2.0.2
Installing image_size 2.0.2
Fetching mime-types-data 3.2020.0425 (was 3.2019.1009)
Installing mime-types-data 3.2020.0425 (was 3.2019.1009)
Fetching mime-types 3.3.1
Installing mime-types 3.3.1
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.9 (x64-mingw32)
Installing nokogiri 1.10.9 (x64-mingw32)
Using thread_safe 0.3.6
Using uuidtools 2.1.5
Using html2doc 1.0.0
Using http-cookie 1.0.3
Fetching iev 0.2.3
Installing iev 0.2.3
Fetching iso-639 0.3.5
Installing iso-639 0.3.5
Using iso639 1.3.2
Using liquid 4.0.3
Using metanorma 1.0.3 (was 1.0.1)
Using roman-numerals 0.3.0
Using sassc 2.2.1 (x64-mingw32)
Fetching isodoc 1.0.24 (was 1.0.23)
Installing isodoc 1.0.24 (was 1.0.23)
Fetching isoics 0.1.8
Installing isoics 0.1.8
Fetching mathml2asciimath 0.0.10 (was 0.0.8)
Installing mathml2asciimath 0.0.10 (was 0.0.8)
Fetching mimemagic 0.3.4
Installing mimemagic 0.3.4
Using relaton-bib 0.9.2
Using relaton-iso-bib 0.9.2 (was 0.9.1)
Using relaton-calconnect 0.7.0
Using relaton-gb 0.12.0
Using relaton-iec 0.10.0
Using relaton-ietf 0.12.1
Using relaton-iso 0.12.1
Using relaton-itu 0.9.0
Fetching rubyzip 2.3.0
Installing rubyzip 2.3.0
Using relaton-nist 0.9.1 (was 0.9.0)
Using relaton-ogc 0.7.3 (was 0.7.1)
Using relaton-omg 0.3.0
Using relaton-un 0.2.1 (was 0.2.0)
Using relaton-w3c 0.1.0
Using relaton 0.11.1 (was 0.11.0)
Using relaton-iev 0.1.5 (was 0.1.4)
Using optout 0.0.2
Using ruby-jing 0.0.1
Fetching sterile 1.0.16 (was 1.0.14)
Installing sterile 1.0.16 (was 1.0.14)
Fetching unicode2latex 0.0.3
Installing unicode2latex 0.0.3
Using metanorma-standoc 1.3.24 (was 1.3.23)
Using metanorma-csa 1.4.8
Using metanorma-csd 1.3.18 (was 1.3.17)
Using metanorma-iso 1.3.22 (was 1.3.21)
Fetching tzinfo 2.0.2
Installing tzinfo 2.0.2
Fetching twitter_cldr 4.4.5
Installing twitter_cldr 4.4.5
Using metanorma-gb 1.3.21 (was 1.3.20)
Using metanorma-generic 1.4.6
Using metanorma-iec 1.0.4 (was 1.0.3)
Using metanorma-ietf 2.0.8 (was 2.0.7)
Using metanorma-itu 1.0.13 (was 1.0.12)
Using metanorma-m3d 1.3.17 (was 1.3.16)
Fetching tzinfo-data 1.2020.1 (was 1.2019.3)
Installing tzinfo-data 1.2020.1 (was 1.2019.3)
Using metanorma-nist 1.0.5 (was 1.0.4)
Using metanorma-ogc 1.0.4
Using metanorma-un 0.3.6 (was 0.3.5)
Using thor 0.20.3
Using relaton-cli 0.9.0
Using metanorma-cli 1.2.11.1 (was 1.2.11)
Bundle updated!
Post-install message from nokogiri:
Nokogiri is built with the packaged libraries: libxml2-2.9.10, libxslt-1.1.34, zlib-1.2.11, libiconv-1.15.

**Comment by opoudjis** [comment] 2020-04-29 12:00
@rggibb Thank you! I'll close the ticket, but I think @ronaldtse is following up with you.

**Closed by opoudjis** 2020-04-29 12:00 UTC
Labels: bug

**Comment by ronaldtse** [comment] 2020-04-29 12:02
Thanks!
